### ISSUE TITLE
How can I set this up with SSR?

### ISSUE THREAD

**Issue by webface** [quavedev/graphql#2]
Is there SSR support?

**Comment by filipenevola** [comment]
Hi, you could instantiate the Apollo Client in your server without any problems.

Is that what you mean?

**Comment by webface** [comment]
@filipenevola I was just wondering if the way the server was instantiated would support hydration as described in the apollo ssr docs. Would just have to try it out. This looks like awesome tools and I enjoyed the you tube video. I'm trying to figure out a way of working with meteor with ssr. Im torn between your lib, pup(no longer maintained) and vulcanjs(seems like they are abandoning meteor to go with Nextjs). I also have more experience with REST than graphql but everything seems to be going graphql these days.

**Comment by webface** [comment]
Another question... would I be able to connect to the api endpoint from React Native...just trying to cover all my bases

**Comment by webface** [comment]
> Hi, you could instantiate the Apollo Client in your server without any problems.
> 
> Is that what you mean?

I tried to implement SSR but couldnt load apolloClient on server. Can you please have a look `server/main.js`. I commented out the code that did not work

```
import { Meteor } from "meteor/meteor";
import { startGraphQLServer } from "meteor/quave:graphql/server";
import { createResolvers } from "meteor/quave:resolvers";
import { DateTimeResolver } from "meteor/quave:custom-type-date-time/DateTimeResolver";
import { DateTimeDefinition } from "meteor/quave:custom-type-date-time/DateTimeDefinition";
import { LinksCollection } from "/imports/api/links";
import { AlbumDefinition } from "../imports/api/albums/AlbumDefinition";
import { SongDefinition } from "../imports/api/songs/SongDefinition";
import { AlbumsCollection } from "../imports/api/albums/AlbumsCollection";
import { SongsCollection } from "../imports/api/songs/SongsCollection";

//SSR try
import { startGraphQLClient } from "meteor/quave:graphql/client";
import {makeExecutableSchema} from 'graphql-tools';
import {getSchema, load} from 'graphql-load';
import React from "react";
import { ApolloProvider } from "@apollo/client";
import { renderToStringWithData } from "@apollo/client/react/ssr";
import { ApolloClient, InMemoryCache } from "@apollo/client";
import { SchemaLink } from "@apollo/client/link/schema";
import "isomorphic-fetch";
import { onPageLoad } from "meteor/server-render";
import { StaticRouter } from "react-router";
import { Helmet } from "react-helmet";
import { ServerStyleSheet } from "styled-components";
import App from "../imports/ui/App";

const log = (error) => console.log("GraphQL server error");

startGraphQLServer({
  typeDefs: [
    DateTimeDefinition,
    AlbumDefinition.toGraphQL(),
    SongDefinition.toGraphQL(),
  ],
  resolvers: [
    DateTimeResolver,
    createResolvers({ collection: AlbumsCollection }),
    createResolvers({ collection: SongsCollection }),
  ],
  log,
});
// onPageLoad(async (sink) => {
//   const apolloClient = startGraphQLClient({ connectToDevTools: true });
//   const stylesheet = new ServerStyleSheet();
//   const app = stylesheet.collectStyles(
//     <ApolloProvider client={apolloClient}>
//       <StaticRouter location={sink.request.url} context={{}}>
//         <App />
//       </StaticRouter>
//     </ApolloProvider>
//   );

//   // NOTE: renderToStringWithData pre-fetches all queries in the component tree. This allows the data
//   // from our GraphQL queries to be ready at render time.
//   const content = await renderToStringWithData(app);
//   const initialState = apolloClient.extract();
//   const helmet = Helmet.renderStatic();

//   sink.appendToHead(helmet.meta.toString());
//   sink.appendToHead(helmet.title.toString());
//   sink.appendToHead(stylesheet.getStyleTags());
//   sink.renderIntoElementById("react-root", content);
//   sink.appendToBody(`
//     <script>
//       window.__APOLLO_STATE__ = ${JSON.stringify(initialState).replace(
//         /</g,
//         "\\u003c"
//       )}
//     </script>
//   `);
// });

```

```
(webapp_server.js:1065) Error running template: Error: ddp-apollo: missing connection param
    at getDefaultMeteorConnection (/Applications/MAMP/htdocs/PROJECTS2021/meteor-graphql-orig/node_modules/apollo-link-ddp/src/client/apollo-link-ddp.js:21:11)
    at new DDPMethodLink (/Applications/MAMP/htdocs/PROJECTS2021/meteor-graphql-orig/node_modules/apollo-link-ddp/src/client/apollo-link-ddp.js:40:18)
    at new DDPLink (/Applications/MAMP/htdocs/PROJECTS2021/meteor-graphql-orig/node_modules/apollo-link-ddp/src/client/apollo-link-ddp.js:131:23)
    at startGraphQLClient (packages/quave:graphql/client.js:20:21)
    at server/main.js:44:24
    at /Users/webface/.meteor/packages/promise/.0.11.2.1xo9zmy.xljqg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by filipenevola** [comment]
I've one of my projects using ApolloClient in the server like this:

```js
import { makeExecutableSchema } from 'graphql-tools';
import { getSchema, load } from 'graphql-load';
import { setup, setupHttpEndpoint } from 'meteor/swydo:ddp-apollo';

import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { SchemaLink } from 'apollo-link-schema';

import '../../setup/server/index';

import { apiAuthMiddleware } from '../../api/apiModule';
import { isAPIModule } from '../../api/apiModuleCommon';
import { bemarkeLogger } from '../../bemarkeLogger';

load({
  typeDefs: [
    MyTypeDefs,
  ],
  resolvers: [
   MyResolver
  ],
});

const schema = makeExecutableSchema({
  ...getSchema(),
  logger: {
    log: error =>
      bemarkeLogger.error({ message: 'GraphQL server error', error }),
  },
});

if (isAPIModule()) {
  setupHttpEndpoint({
    schema,
    authMiddleware: apiAuthMiddleware,
  });
} else {
  setup({ schema });
}

export const getApolloServerClient = () =>
  new ApolloClient({
    ssrMode: true,
    cache: new InMemoryCache(),
    link: new SchemaLink({ schema }),
  });

```

then later I use like this:

```js
  const {
    data: { publishedStores },
  } = await getApolloServerClient().query({
    query: gql`
      query PublishedStores {
        publishedStores {
          _id
          name
          storeCurrentBillTotal
          timezone
          city
          user {
            lastLoginAt
          }
          isWhiteLabel
          customAnticipationAmount
          finishedOrdersMonth {
            ...OrderReport
          }
        }
      }
      ${OrderFragments.OrderReport}
    `,
  });
```

Sorry for the long time to respond, somehow I lost this notification.
